version: '3.8'

services:
  honeyroot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: honeyroot-x
    restart: unless-stopped
    ports:
      - "22:2222"
    environment:
      - VT_API_KEY=your_virustotal_api_key_here
    volumes:
      - ./logs:/opt/honeyroot/logs
