input {
  file {
    path => "/usr/share/logstash/logs/honeypot.json"
    start_position => "beginning"
    codec => json
  }
}

filter {
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }
  
  if [payload][ip] {
    geoip {
      source => "[payload][ip]"
      target => "geoip"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "honeyroot-x-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
